.github/workflows/API_SPimport pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load your data (replace 'your_data.csv' with the actual file path)
df = pd.read_csv('your_data.csv')

# 1. Visualizing the distribution of a continuous variable (Age)
plt.figure(figsize=(10,6))
sns.histplot(df['Age'], kde=True, bins=20, color='blue', stat='density', discrete=False)

# Adding titles and labels
plt.title('Age Distribution', fontsize=16)
plt.xlabel('Age', fontsize=14)
plt.ylabel('Density', fontsize=14)

# Show plot
plt.show()

# 2. Visualizing the distribution of a categorical variable (Gender)
plt.figure(figsize=(8,6))
sns.countplot(data=df, x='Gender', palette='Set2')

# Adding titles and labels
plt.title('Gender Distribution', fontsize=16)
plt.xlabel('Gender', fontsize=14)
plt.ylabel('Count', fontsize=14)

# Show plot
plt.show()
.POP.TOTL_DS2_en_csv_v2_900.csv
